exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.15.0"  # replace with latest tag on GitHub
    hooks:
    -   id: django-upgrade
        args: [--target-version, "4.2"]   # Replace with Django version
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.8
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
