[tool.poetry]
name = "django-rest-elasticsearch"
version = "0.4.1"
description = "Elasticsearch support for Django REST Framework"
authors = ["Somebody"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2.13"  # pin to 4.2.13 because in 4.2.14 django fixes a path traversal vulnerability https://docs.djangoproject.com/en/5.0/releases/4.2.14/#cve-2024-39330-potential-directory-traversal-via-storage-save that makes easy-yhumbanils library to fail
djangorestframework = "^3.14.0"
elasticsearch-dsl = ">=7.0.0,<8.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
pytest-runner = "^6.0.1"
coreapi = "^2.3.3"
pytz = "^2023.3.post1"
six = "^1.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
